
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Minilab1(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output	reg	     [6:0]		HEX0,
	output	reg	     [6:0]		HEX1,
	output	reg	     [6:0]		HEX2,
	output	reg	     [6:0]		HEX3,
	output	reg	     [6:0]		HEX4,
	output	reg	     [6:0]		HEX5,
	
	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW
);

//=======================================================
//  Parameters
//=======================================================

localparam DATA_WIDTH = 8;
localparam DIM = 8;
localparam DEPTH = 8;

// Top-level state machine
localparam S_IDLE  = 2'd0;
localparam S_FETCH = 2'd1;
localparam S_EXEC  = 2'd2;
localparam S_DONE  = 2'd3;

//=======================================================
//  Hex decoder function
//=======================================================

function [6:0] hex_decode;
  input [3:0] val;
  case (val)
    4'd0:  hex_decode = 7'b1000000;  // 0
    4'd1:  hex_decode = 7'b1111001;  // 1
    4'd2:  hex_decode = 7'b0100100;  // 2
    4'd3:  hex_decode = 7'b0110000;  // 3
    4'd4:  hex_decode = 7'b0011001;  // 4
    4'd5:  hex_decode = 7'b0010010;  // 5
    4'd6:  hex_decode = 7'b0000010;  // 6
    4'd7:  hex_decode = 7'b1111000;  // 7
    4'd8:  hex_decode = 7'b0000000;  // 8
    4'd9:  hex_decode = 7'b0011000;  // 9
    4'd10: hex_decode = 7'b0001000;  // A
    4'd11: hex_decode = 7'b0000011;  // b
    4'd12: hex_decode = 7'b1000110;  // C
    4'd13: hex_decode = 7'b0100001;  // d
    4'd14: hex_decode = 7'b0000110;  // E
    4'd15: hex_decode = 7'b0001110;  // F
    default: hex_decode = 7'b1111111; // off
  endcase
endfunction

//=======================================================
//  REG/WIRE declarations
//=======================================================

wire rst_n;
assign rst_n = KEY[0];

reg [1:0] state;
reg start;

// Avalon-MM wires (data_fetcher <-> memory)
wire [31:0] mem_address;
wire        mem_read;
wire [63:0] mem_readdata;
wire        mem_readdatavalid;
wire        mem_waitrequest;

// Data fetcher -> matrix_vector_multiplier wires
wire [7:0]  fifo_data;
wire [3:0]  fifo_sel;
wire        fifo_wren;
wire        fetch_done;

// Matrix-vector multiplier results
wire [DATA_WIDTH*3-1:0] result [0:DIM-1];
wire                    mul_done;

//=======================================================
//  Module instantiation
//=======================================================

// Memory (Avalon-MM slave with ROM)
mem_wrapper mem (
  .clk(CLOCK_50),
  .reset_n(rst_n),
  .address(mem_address),
  .read(mem_read),
  .readdata(mem_readdata),
  .readdatavalid(mem_readdatavalid),
  .waitrequest(mem_waitrequest)
);

// Data fetcher (Avalon-MM master)
data_fetcher fetcher (
  .clk(CLOCK_50),
  .rst_n(rst_n),
  .start(start),
  .mem_address(mem_address),
  .mem_read(mem_read),
  .mem_readdata(mem_readdata),
  .mem_readdatavalid(mem_readdatavalid),
  .mem_waitrequest(mem_waitrequest),
  .fifo_data(fifo_data),
  .fifo_sel(fifo_sel),
  .fifo_wren(fifo_wren),
  .done(fetch_done)
);

// Matrix-vector multiplier (8 A-FIFOs + 1 B-FIFO + 8 MACs)
matrix_vector_multiplier #(
  .DATA_WIDTH(DATA_WIDTH),
  .DIM(DIM),
  .DEPTH(DEPTH)
) multiplier (
  .clk(CLOCK_50),
  .rst_n(rst_n),
  .fifo_data(fifo_data),
  .fifo_sel(fifo_sel),
  .fifo_wren(fifo_wren),
  .fetch_done(fetch_done),
  .result(result),
  .done(mul_done)
);

//=======================================================
//  Top-level state machine
//
//  S_IDLE  : Pulse start to data_fetcher
//  S_FETCH : Wait for data_fetcher to fill all FIFOs
//  S_EXEC  : Wait for matrix_vector_multiplier to finish
//  S_DONE  : Results ready — display on 7-seg
//=======================================================

always @(posedge CLOCK_50 or negedge rst_n) begin
  if (~rst_n) begin
    state <= S_IDLE;
    start <= 1'b0;
  end
  else begin
    case (state)
      S_IDLE: begin
        start <= 1'b1;
        state <= S_FETCH;
      end
      S_FETCH: begin
        start <= 1'b0;
        if (fetch_done)
          state <= S_EXEC;
      end
      S_EXEC: begin
        if (mul_done)
          state <= S_DONE;
      end
      S_DONE: begin
        // Hold — results displayed via switches
      end
    endcase
  end
end

//=======================================================
//  Display: select MAC output with SW[2:0]
//
//  SW[2:0] = 0-7 selects which C[i] result to show
//  HEX5..HEX0 shows the 24-bit value in hex
//  Display is active when in DONE state
//=======================================================

reg [DATA_WIDTH*3-1:0] display_val;

always @(*) begin
  case (SW[2:0])
    3'd0: display_val = result[0];
    3'd1: display_val = result[1];
    3'd2: display_val = result[2];
    3'd3: display_val = result[3];
    3'd4: display_val = result[4];
    3'd5: display_val = result[5];
    3'd6: display_val = result[6];
    3'd7: display_val = result[7];
  endcase
end

always @(*) begin
  if (state == S_DONE) begin
    HEX0 = hex_decode(display_val[3:0]);
    HEX1 = hex_decode(display_val[7:4]);
    HEX2 = hex_decode(display_val[11:8]);
    HEX3 = hex_decode(display_val[15:12]);
    HEX4 = hex_decode(display_val[19:16]);
    HEX5 = hex_decode(display_val[23:20]);
  end
  else begin
    HEX0 = 7'b1111111;
    HEX1 = 7'b1111111;
    HEX2 = 7'b1111111;
    HEX3 = 7'b1111111;
    HEX4 = 7'b1111111;
    HEX5 = 7'b1111111;
  end
end

//=======================================================
//  LEDs: show top-level state
//
//  LEDR[1:0] = state (00=IDLE, 01=FETCH, 10=EXEC, 11=DONE)
//  LEDR[9]   = mul_done
//  LEDR[8]   = fetch_done
//=======================================================

assign LEDR[1:0] = state;
assign LEDR[7:2] = 6'd0;
assign LEDR[8]   = fetch_done;
assign LEDR[9]   = mul_done;

endmodule
